server:
  port: 8081
spring.jpa.database-platform:
  org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto:
  update
spring.jpa.generate-ddl:
  true
spring.datasource.driverClassName:
  com.mysql.cj.jdbc.Driver
spring.datasource.url:
  jdbc:mysql://localhost:3306/user
spring:
  jpa:
    show-sql=true:
spring.datasource.username:
  root
spring.datasource.password:
  root